// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarkerMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MarkerMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace treadmill {

namespace {

const ::google::protobuf::Descriptor* MarkerMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MarkerMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MarkerMessage_2eproto() {
  protobuf_AddDesc_MarkerMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MarkerMessage.proto");
  GOOGLE_CHECK(file != NULL);
  MarkerMessage_descriptor_ = file->message_type(0);
  static const int MarkerMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, camera_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, markerfound_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, error_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, error_y_),
  };
  MarkerMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MarkerMessage_descriptor_,
      MarkerMessage::default_instance_,
      MarkerMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkerMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MarkerMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MarkerMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MarkerMessage_descriptor_, &MarkerMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MarkerMessage_2eproto() {
  delete MarkerMessage::default_instance_;
  delete MarkerMessage_reflection_;
}

void protobuf_AddDesc_MarkerMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023MarkerMessage.proto\022\ttreadmill\"o\n\rMark"
    "erMessage\022\021\n\tcamera_id\030\001 \001(\t\022\023\n\013markerFo"
    "und\030\002 \002(\010\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\017\n\007error"
    "_x\030\005 \001(\021\022\017\n\007error_y\030\006 \001(\021", 145);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MarkerMessage.proto", &protobuf_RegisterTypes);
  MarkerMessage::default_instance_ = new MarkerMessage();
  MarkerMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MarkerMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MarkerMessage_2eproto {
  StaticDescriptorInitializer_MarkerMessage_2eproto() {
    protobuf_AddDesc_MarkerMessage_2eproto();
  }
} static_descriptor_initializer_MarkerMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MarkerMessage::kCameraIdFieldNumber;
const int MarkerMessage::kMarkerFoundFieldNumber;
const int MarkerMessage::kXFieldNumber;
const int MarkerMessage::kYFieldNumber;
const int MarkerMessage::kErrorXFieldNumber;
const int MarkerMessage::kErrorYFieldNumber;
#endif  // !_MSC_VER

MarkerMessage::MarkerMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MarkerMessage::InitAsDefaultInstance() {
}

MarkerMessage::MarkerMessage(const MarkerMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MarkerMessage::SharedCtor() {
  _cached_size_ = 0;
  camera_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  markerfound_ = false;
  x_ = 0;
  y_ = 0;
  error_x_ = 0;
  error_y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MarkerMessage::~MarkerMessage() {
  SharedDtor();
}

void MarkerMessage::SharedDtor() {
  if (camera_id_ != &::google::protobuf::internal::kEmptyString) {
    delete camera_id_;
  }
  if (this != default_instance_) {
  }
}

void MarkerMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MarkerMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MarkerMessage_descriptor_;
}

const MarkerMessage& MarkerMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MarkerMessage_2eproto();
  return *default_instance_;
}

MarkerMessage* MarkerMessage::default_instance_ = NULL;

MarkerMessage* MarkerMessage::New() const {
  return new MarkerMessage;
}

void MarkerMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_camera_id()) {
      if (camera_id_ != &::google::protobuf::internal::kEmptyString) {
        camera_id_->clear();
      }
    }
    markerfound_ = false;
    x_ = 0;
    y_ = 0;
    error_x_ = 0;
    error_y_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MarkerMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string camera_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_camera_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->camera_id().data(), this->camera_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_markerFound;
        break;
      }

      // required bool markerFound = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_markerFound:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &markerfound_)));
          set_has_markerfound();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_x;
        break;
      }

      // optional int32 x = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_y;
        break;
      }

      // optional int32 y = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_error_x;
        break;
      }

      // optional sint32 error_x = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_error_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &error_x_)));
          set_has_error_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_error_y;
        break;
      }

      // optional sint32 error_y = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_error_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &error_y_)));
          set_has_error_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MarkerMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string camera_id = 1;
  if (has_camera_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->camera_id().data(), this->camera_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->camera_id(), output);
  }

  // required bool markerFound = 2;
  if (has_markerfound()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->markerfound(), output);
  }

  // optional int32 x = 3;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->x(), output);
  }

  // optional int32 y = 4;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->y(), output);
  }

  // optional sint32 error_x = 5;
  if (has_error_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->error_x(), output);
  }

  // optional sint32 error_y = 6;
  if (has_error_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(6, this->error_y(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MarkerMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string camera_id = 1;
  if (has_camera_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->camera_id().data(), this->camera_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->camera_id(), target);
  }

  // required bool markerFound = 2;
  if (has_markerfound()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->markerfound(), target);
  }

  // optional int32 x = 3;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->x(), target);
  }

  // optional int32 y = 4;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->y(), target);
  }

  // optional sint32 error_x = 5;
  if (has_error_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(5, this->error_x(), target);
  }

  // optional sint32 error_y = 6;
  if (has_error_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(6, this->error_y(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MarkerMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string camera_id = 1;
    if (has_camera_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->camera_id());
    }

    // required bool markerFound = 2;
    if (has_markerfound()) {
      total_size += 1 + 1;
    }

    // optional int32 x = 3;
    if (has_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->x());
    }

    // optional int32 y = 4;
    if (has_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->y());
    }

    // optional sint32 error_x = 5;
    if (has_error_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->error_x());
    }

    // optional sint32 error_y = 6;
    if (has_error_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->error_y());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MarkerMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MarkerMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MarkerMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MarkerMessage::MergeFrom(const MarkerMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_camera_id()) {
      set_camera_id(from.camera_id());
    }
    if (from.has_markerfound()) {
      set_markerfound(from.markerfound());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_error_x()) {
      set_error_x(from.error_x());
    }
    if (from.has_error_y()) {
      set_error_y(from.error_y());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MarkerMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MarkerMessage::CopyFrom(const MarkerMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarkerMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;

  return true;
}

void MarkerMessage::Swap(MarkerMessage* other) {
  if (other != this) {
    std::swap(camera_id_, other->camera_id_);
    std::swap(markerfound_, other->markerfound_);
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(error_x_, other->error_x_);
    std::swap(error_y_, other->error_y_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MarkerMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MarkerMessage_descriptor_;
  metadata.reflection = MarkerMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace treadmill

// @@protoc_insertion_point(global_scope)
